language: java
jdk:
- oraclejdk8
sudo: required


before_script:
  - wget http://services.gradle.org/distributions/gradle-4.7-bin.zip
  - unzip gradle-4.7-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.7
  - export PATH=$GRADLE_HOME/bin:$PATH

addons:
  sonarcloud:
    organization: "sitoriesrepo"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
    branches:
    - develop
script:
- gradle test
- sonar-scanner
- gradle check

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="f2e5f84a-0527-456d-8588-69c36bc81479"

notifications:
  email: true
